# Generated by Django 6.0.4 on 2026-05-14 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mood', '0002_feedback_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('Sleep', 'Better Sleep'), ('Stress', 'Stress Relief'), ('Self-Love', 'Self-Love'), ('Focus', 'Deep Focus'), ('Anxiety', 'Anxiety'), ('Exercise', 'Exercise'), ('Hydration', 'Hydration'), ('Social', 'Social'), ('Gratitude', 'Gratitude')], default='Sleep', max_length=20),
        ),
        migrations.AddField(
            model_name='article',
            name='summary',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
