# Generated by Django 6.0.4 on 2026-05-14 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mood', '0003_article_category_article_summary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='content',
        ),
        migrations.AddField(
            model_name='article',
            name='external_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
