# Generated by Django 6.0.4 on 2026-05-05 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mood', '0004_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
    ]
