# Generated by Django 6.0.4 on 2026-05-05 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mood', '0005_profile_birthday'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mood',
            old_name='description',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='mood',
            old_name='datetime',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='mood',
            name='mood_type',
        ),
        migrations.AddField(
            model_name='mood',
            name='category',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='mood',
            name='mood_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='mood',
            name='song',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='mood',
            name='intensity',
            field=models.IntegerField(default=3),
        ),
    ]
