# Generated by Django 6.0.4 on 2026-05-05 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mood', '0006_rename_description_mood_content_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mood',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='mood',
            name='content',
            field=models.TextField(blank=True),
        ),
    ]
