# Generated by Django 6.0.4 on 2026-06-07 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_favorite_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='screenshot',
            field=models.ImageField(blank=True, null=True, upload_to='feedback/'),
        ),
    ]
