# Generated by Django 6.0.4 on 2026-06-07 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_feedback_screenshot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='screenshot',
        ),
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
    ]
