# Generated by Django 6.0.3 on 2026-06-12 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_feedback_screenshot_profile_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('mood_category', models.CharField(max_length=50)),
                ('audio_file', models.FileField(upload_to='music/')),
            ],
        ),
        migrations.RemoveField(
            model_name='moodentry',
            name='artist',
        ),
        migrations.RemoveField(
            model_name='moodentry',
            name='music_link',
        ),
        migrations.RemoveField(
            model_name='moodentry',
            name='song_title',
        ),
        migrations.AddField(
            model_name='moodentry',
            name='selected_music',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.music'),
        ),
    ]
