# Generated by Django 6.0.3 on 2026-04-29 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_moodentry_intensity'),
    ]

    operations = [
        migrations.AddField(
            model_name='moodentry',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='mood_photos/'),
        ),
    ]
