# Generated by Django 6.0.4 on 2026-06-16 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_music_remove_moodentry_artist_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='mood_category',
            field=models.CharField(choices=[('Happy', 'Happy'), ('Sad', 'Sad'), ('Neutral', 'Neutral'), ('Angry', 'Angry')], max_length=20),
        ),
    ]
