# Generated by Django 6.0.3 on 2026-06-17 14:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_music_mood_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='moodentry',
            name='entry_date',
            field=models.DateField(default=datetime.date(2026, 6, 17)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('basics', 'Mental Health Basics'), ('motivation', 'Motivation & Positive Mindset'), ('relationships', 'Relationships & Social Well-Being'), ('stress', 'Stress & Anxiety Management'), ('selfcare', 'Self-Care & Daily Habits')], default='basics', max_length=50),
        ),
    ]
