# Generated by Django 6.0.3 on 2026-04-29 08:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_moodentry_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moodentry',
            name='photo',
        ),
        migrations.CreateModel(
            name='MoodPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='mood_photos/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('mood_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='users.moodentry')),
            ],
        ),
    ]
