# Generated by Django 6.0.3 on 2026-04-29 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_moodentry_photo_moodphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='moodentry',
            name='artist',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='moodentry',
            name='music_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='moodentry',
            name='song_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
