# Generated by Django 6.0.3 on 2026-06-17 14:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_moodentry_entry_date_alter_article_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moodentry',
            name='entry_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
