# Generated by Django 6.0.4 on 2026-06-17 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_moodentry_entry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moodentry',
            name='category',
            field=models.CharField(blank=True, choices=[('sad', 'Sad'), ('neutral', 'Neutral'), ('happy', 'Happy'), ('angry', 'Angry')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='moodentry',
            name='mood',
            field=models.CharField(choices=[('sad', 'Sad'), ('sick', 'Sick'), ('cringe', 'Cringe'), ('tired', 'Tired'), ('exhausted', 'Exhausted'), ('guilty', 'Guilty'), ('afraid', 'Afraid'), ('neutral', 'Neutral'), ('shy', 'Shy'), ('sleepy', 'Sleepy'), ('curious', 'Curious'), ('happy', 'Happy'), ('kiss', 'Kiss'), ('yeah', 'Yeah'), ('fighting', 'Fighting'), ('good', 'Good'), ('lovely', 'Lovely'), ('admire', 'Admire'), ('warm', 'Warm'), ('energetic', 'Energetic'), ('motivated', 'Motivated'), ('angry', 'Angry'), ('shock', 'Shock'), ('trick', 'Trick'), ('awkward', 'Awkward')], max_length=50),
        ),
    ]
